// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging_timer_example.proto

package com.jbhunt.messaging.proto;

/**
 * Protobuf type {@code jbhunt.Timer}
 */
public final class Timer extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:jbhunt.Timer)
    TimerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Timer.newBuilder() to construct.
  private Timer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Timer() {
    name_ = "";
    statusType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Timer();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Timer(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 16: {

            value_ = input.readInt32();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            statusType_ = rawValue;
            break;
          }
          case 34: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timerDatetime_ != null) {
              subBuilder = timerDatetime_.toBuilder();
            }
            timerDatetime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timerDatetime_);
              timerDatetime_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jbhunt.messaging.proto.MessagingTimerExample.internal_static_jbhunt_Timer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jbhunt.messaging.proto.MessagingTimerExample.internal_static_jbhunt_Timer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jbhunt.messaging.proto.Timer.class, com.jbhunt.messaging.proto.Timer.Builder.class);
  }

  /**
   * Protobuf enum {@code jbhunt.Timer.StatusType}
   */
  public enum StatusType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Active = 0;</code>
     */
    Active(0),
    /**
     * <code>Inactive = 1;</code>
     */
    Inactive(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Active = 0;</code>
     */
    public static final int Active_VALUE = 0;
    /**
     * <code>Inactive = 1;</code>
     */
    public static final int Inactive_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StatusType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static StatusType forNumber(int value) {
      switch (value) {
        case 0: return Active;
        case 1: return Inactive;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StatusType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StatusType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StatusType>() {
            public StatusType findValueByNumber(int number) {
              return StatusType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jbhunt.messaging.proto.Timer.getDescriptor().getEnumTypes().get(0);
    }

    private static final StatusType[] VALUES = values();

    public static StatusType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private StatusType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:jbhunt.Timer.StatusType)
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private int value_;
  /**
   * <code>int32 value = 2;</code>
   * @return The value.
   */
  @java.lang.Override
  public int getValue() {
    return value_;
  }

  public static final int STATUS_TYPE_FIELD_NUMBER = 3;
  private int statusType_;
  /**
   * <code>.jbhunt.Timer.StatusType status_type = 3;</code>
   * @return The enum numeric value on the wire for statusType.
   */
  @java.lang.Override public int getStatusTypeValue() {
    return statusType_;
  }
  /**
   * <code>.jbhunt.Timer.StatusType status_type = 3;</code>
   * @return The statusType.
   */
  @java.lang.Override public com.jbhunt.messaging.proto.Timer.StatusType getStatusType() {
    @SuppressWarnings("deprecation")
    com.jbhunt.messaging.proto.Timer.StatusType result = com.jbhunt.messaging.proto.Timer.StatusType.valueOf(statusType_);
    return result == null ? com.jbhunt.messaging.proto.Timer.StatusType.UNRECOGNIZED : result;
  }

  public static final int TIMER_DATETIME_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp timerDatetime_;
  /**
   * <code>.google.protobuf.Timestamp timer_datetime = 4;</code>
   * @return Whether the timerDatetime field is set.
   */
  @java.lang.Override
  public boolean hasTimerDatetime() {
    return timerDatetime_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp timer_datetime = 4;</code>
   * @return The timerDatetime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimerDatetime() {
    return timerDatetime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timerDatetime_;
  }
  /**
   * <code>.google.protobuf.Timestamp timer_datetime = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimerDatetimeOrBuilder() {
    return getTimerDatetime();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (value_ != 0) {
      output.writeInt32(2, value_);
    }
    if (statusType_ != com.jbhunt.messaging.proto.Timer.StatusType.Active.getNumber()) {
      output.writeEnum(3, statusType_);
    }
    if (timerDatetime_ != null) {
      output.writeMessage(4, getTimerDatetime());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (value_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, value_);
    }
    if (statusType_ != com.jbhunt.messaging.proto.Timer.StatusType.Active.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, statusType_);
    }
    if (timerDatetime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getTimerDatetime());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jbhunt.messaging.proto.Timer)) {
      return super.equals(obj);
    }
    com.jbhunt.messaging.proto.Timer other = (com.jbhunt.messaging.proto.Timer) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getValue()
        != other.getValue()) return false;
    if (statusType_ != other.statusType_) return false;
    if (hasTimerDatetime() != other.hasTimerDatetime()) return false;
    if (hasTimerDatetime()) {
      if (!getTimerDatetime()
          .equals(other.getTimerDatetime())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue();
    hash = (37 * hash) + STATUS_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + statusType_;
    if (hasTimerDatetime()) {
      hash = (37 * hash) + TIMER_DATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getTimerDatetime().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jbhunt.messaging.proto.Timer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jbhunt.messaging.proto.Timer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jbhunt.messaging.proto.Timer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jbhunt.messaging.proto.Timer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jbhunt.messaging.proto.Timer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jbhunt.messaging.proto.Timer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jbhunt.messaging.proto.Timer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jbhunt.messaging.proto.Timer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jbhunt.messaging.proto.Timer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jbhunt.messaging.proto.Timer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jbhunt.messaging.proto.Timer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jbhunt.messaging.proto.Timer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jbhunt.messaging.proto.Timer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code jbhunt.Timer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:jbhunt.Timer)
      com.jbhunt.messaging.proto.TimerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jbhunt.messaging.proto.MessagingTimerExample.internal_static_jbhunt_Timer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jbhunt.messaging.proto.MessagingTimerExample.internal_static_jbhunt_Timer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jbhunt.messaging.proto.Timer.class, com.jbhunt.messaging.proto.Timer.Builder.class);
    }

    // Construct using com.jbhunt.messaging.proto.Timer.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      value_ = 0;

      statusType_ = 0;

      if (timerDatetimeBuilder_ == null) {
        timerDatetime_ = null;
      } else {
        timerDatetime_ = null;
        timerDatetimeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jbhunt.messaging.proto.MessagingTimerExample.internal_static_jbhunt_Timer_descriptor;
    }

    @java.lang.Override
    public com.jbhunt.messaging.proto.Timer getDefaultInstanceForType() {
      return com.jbhunt.messaging.proto.Timer.getDefaultInstance();
    }

    @java.lang.Override
    public com.jbhunt.messaging.proto.Timer build() {
      com.jbhunt.messaging.proto.Timer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.jbhunt.messaging.proto.Timer buildPartial() {
      com.jbhunt.messaging.proto.Timer result = new com.jbhunt.messaging.proto.Timer(this);
      result.name_ = name_;
      result.value_ = value_;
      result.statusType_ = statusType_;
      if (timerDatetimeBuilder_ == null) {
        result.timerDatetime_ = timerDatetime_;
      } else {
        result.timerDatetime_ = timerDatetimeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jbhunt.messaging.proto.Timer) {
        return mergeFrom((com.jbhunt.messaging.proto.Timer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jbhunt.messaging.proto.Timer other) {
      if (other == com.jbhunt.messaging.proto.Timer.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getValue() != 0) {
        setValue(other.getValue());
      }
      if (other.statusType_ != 0) {
        setStatusTypeValue(other.getStatusTypeValue());
      }
      if (other.hasTimerDatetime()) {
        mergeTimerDatetime(other.getTimerDatetime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jbhunt.messaging.proto.Timer parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jbhunt.messaging.proto.Timer) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int value_ ;
    /**
     * <code>int32 value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public int getValue() {
      return value_;
    }
    /**
     * <code>int32 value = 2;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(int value) {
      
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      
      value_ = 0;
      onChanged();
      return this;
    }

    private int statusType_ = 0;
    /**
     * <code>.jbhunt.Timer.StatusType status_type = 3;</code>
     * @return The enum numeric value on the wire for statusType.
     */
    @java.lang.Override public int getStatusTypeValue() {
      return statusType_;
    }
    /**
     * <code>.jbhunt.Timer.StatusType status_type = 3;</code>
     * @param value The enum numeric value on the wire for statusType to set.
     * @return This builder for chaining.
     */
    public Builder setStatusTypeValue(int value) {
      
      statusType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.jbhunt.Timer.StatusType status_type = 3;</code>
     * @return The statusType.
     */
    @java.lang.Override
    public com.jbhunt.messaging.proto.Timer.StatusType getStatusType() {
      @SuppressWarnings("deprecation")
      com.jbhunt.messaging.proto.Timer.StatusType result = com.jbhunt.messaging.proto.Timer.StatusType.valueOf(statusType_);
      return result == null ? com.jbhunt.messaging.proto.Timer.StatusType.UNRECOGNIZED : result;
    }
    /**
     * <code>.jbhunt.Timer.StatusType status_type = 3;</code>
     * @param value The statusType to set.
     * @return This builder for chaining.
     */
    public Builder setStatusType(com.jbhunt.messaging.proto.Timer.StatusType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      statusType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.jbhunt.Timer.StatusType status_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatusType() {
      
      statusType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp timerDatetime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timerDatetimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timer_datetime = 4;</code>
     * @return Whether the timerDatetime field is set.
     */
    public boolean hasTimerDatetime() {
      return timerDatetimeBuilder_ != null || timerDatetime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timer_datetime = 4;</code>
     * @return The timerDatetime.
     */
    public com.google.protobuf.Timestamp getTimerDatetime() {
      if (timerDatetimeBuilder_ == null) {
        return timerDatetime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timerDatetime_;
      } else {
        return timerDatetimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timer_datetime = 4;</code>
     */
    public Builder setTimerDatetime(com.google.protobuf.Timestamp value) {
      if (timerDatetimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timerDatetime_ = value;
        onChanged();
      } else {
        timerDatetimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timer_datetime = 4;</code>
     */
    public Builder setTimerDatetime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timerDatetimeBuilder_ == null) {
        timerDatetime_ = builderForValue.build();
        onChanged();
      } else {
        timerDatetimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timer_datetime = 4;</code>
     */
    public Builder mergeTimerDatetime(com.google.protobuf.Timestamp value) {
      if (timerDatetimeBuilder_ == null) {
        if (timerDatetime_ != null) {
          timerDatetime_ =
            com.google.protobuf.Timestamp.newBuilder(timerDatetime_).mergeFrom(value).buildPartial();
        } else {
          timerDatetime_ = value;
        }
        onChanged();
      } else {
        timerDatetimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timer_datetime = 4;</code>
     */
    public Builder clearTimerDatetime() {
      if (timerDatetimeBuilder_ == null) {
        timerDatetime_ = null;
        onChanged();
      } else {
        timerDatetime_ = null;
        timerDatetimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timer_datetime = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimerDatetimeBuilder() {
      
      onChanged();
      return getTimerDatetimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp timer_datetime = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimerDatetimeOrBuilder() {
      if (timerDatetimeBuilder_ != null) {
        return timerDatetimeBuilder_.getMessageOrBuilder();
      } else {
        return timerDatetime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timerDatetime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timer_datetime = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimerDatetimeFieldBuilder() {
      if (timerDatetimeBuilder_ == null) {
        timerDatetimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimerDatetime(),
                getParentForChildren(),
                isClean());
        timerDatetime_ = null;
      }
      return timerDatetimeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:jbhunt.Timer)
  }

  // @@protoc_insertion_point(class_scope:jbhunt.Timer)
  private static final com.jbhunt.messaging.proto.Timer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jbhunt.messaging.proto.Timer();
  }

  public static com.jbhunt.messaging.proto.Timer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Timer>
      PARSER = new com.google.protobuf.AbstractParser<Timer>() {
    @java.lang.Override
    public Timer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Timer(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Timer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Timer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.jbhunt.messaging.proto.Timer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

